version: "3.9"
services:
  db:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - /home
    ports:
      - 27017:27017
    restart: unless-stopped
  be:
    build:
      dockerfile: ./docker/Dockerfile.nest
      context: .
    command: npm run start:dev
    ports:
      - 3000:3000
    restart: always
